- .changeset/eighty-queens-repeat.md
- packages/babel-plugin/src/index.ts
Turns out `path.stop()` stops traversal of a node globally, not just for the calling plugin 😅.  Removing them in favour of simple early returns resolves the issue. 
This would cause other plugins (e.g. `preset-react`, `preset-typescript`, etc) to not complete their compilation, leading to errors like the following.
```
Module parse failed: Unexpected token (8:9)
File was processed with these loaders:
* ./node_modules/@next/react-refresh-utils/loader.js
* ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
|   pageProps
| }) {
>   return <Component {...pageProps} __self={this} __source={{
|     fileName: _jsxFileName,
|     lineNumber: 4,
```
Resolves #40
> Fix issue where babel-plugin would cause other plugins to exit early

- .changeset/dirty-beans-dance.md
- packages/sprinkles/src/createAtomsFn.ts
- tests/sprinkles/index.css.ts
- tests/sprinkles/sprinkles.test.ts
Fixes bug where falsey values such as `opacity: 0` would not resolve classes via the conditional object or responsive array syntax.
```ts
export const atoms = createAtomicStyles({
defaultCondition: 'mobile',
conditions: {
mobile: {},
desktop: {
'@media': 'screen and (min-width: 786px)',
},
},
responsiveArray: ['mobile', 'desktop'],
properties: {
opacity: [0, 1],
},
});
```
> Sprinkles: Support resolving falsey values for conditional atoms

- .changeset/calm-lamps-do.md
- .changeset/silent-pugs-sell.md
- packages/css/src/index.ts
- packages/css/src/transformCss.ts
- packages/css/src/types.ts
- packages/sprinkles/src/index.ts
- tests/E2E/__snapshots__/stylesheets.test.ts.snap
- tests/sprinkles/index.css.ts
- tests/sprinkles/sprinkles.test.ts
This change makes it possible to pass theme vars from `createThemeContract`/`createTheme` to be passed to atomic styles properties.
> Sprinkles: Allow theme vars in atomic properties

- .changeset/sweet-turkeys-rhyme.md
- fixtures/themed/src/shared.css.ts
- packages/esbuild-plugin/src/index.ts
[By default](https://esbuild.github.io/content-types/#javascript) esbuild will use the `js` loader for any content returned from an `onLoad` callback.
This change attempts to detect whether the file being loaded ends in `.ts` or `.tsx` and switches to use the ts loader as documented here:
https://esbuild.github.io/content-types/#typescript
Files that are not detected as `.ts` files will use the current default behaviour of using the `js` loader.
**Example error:**
```
> src/App.css.ts:9:5: error: Expected ";" but found "Hello"
9 │ type Hello = string;
╵      ~~~~~
```
> Compile .css.ts files with ts loader

- site/src/Code/Code.tsx
- site/src/HomePage/HomePage.tsx
- site/src/render.tsx
- site/webpack.config.js
- Contrast of code block titles in light mode
- Heading hierarchy skipped (previously h1 to h4, now h1 to h2)
- 404 on default favicon
- Missing doctype and html lang attribute
- Disabled webpack bundle analyser in CI
> Site: More improvements

- .changeset/rare-olives-decide.md
This is needed due to a missed changeset in #70
> Force release of webpack and esbuild plugins

- site/src/Code/Code.tsx
This fixes an issue where the keyword `large` isn't underlined in the hero code snippet anymore.
> Site: Fix missing error underline

- .changeset/curly-bats-allow.md
- packages/esbuild-plugin/src/index.ts
Add `processCss` plugin option to allow further processing of css while bundling.
**Example for postcss with autoprefixer:**
```js
// build.js
const { vanillaExtractPlugin } = require('@vanilla-extract/esbuild-plugin');
const postcss = require('postcss');
const autoprefixer = require('autoprefixer');
require('esbuild').build({
entryPoints: ['app.ts'],
bundle: true,
plugins: [vanillaExtractPlugin({
processCss: async (css) => {
return (await postcss([autoprefixer])
.process(css, { from: undefined /* suppress source map warning */ })
).css
}
})],
outfile: 'out.js',
}).catch(() => process.exit(1))
```
> Add processCss callback option for esbuild plugin

- .changeset/ninety-impalas-stare.md
- packages/sprinkles/src/types.ts
Fixes #250
I'm not sure this is correct, but in case you think the issue is valid and exporting is an ok solution, here's the fix.
> Sprinkles: Export ResponsiveArray types

- .changeset/strong-coats-float.md
- packages/webpack-plugin/src/compiler.ts
- packages/webpack-plugin/src/index.ts
Since removing child compilations within child compilations the compiler cache no longer gets used.
> Remove webpack-plugin compiler cache

- .changeset/stupid-news-work.md
- packages/vite-plugin/src/index.ts
Should be iterating over the array values instead of indices.
Found out about this when testing the fix for https://github.com/vitejs/vite/issues/3216
> vite-plugin: fix addWatchFiles call

- .changeset/short-mayflies-reflect.md
- packages/vite-plugin/package.json
- packages/vite-plugin/src/index.ts
- yarn.lock
Fixes vitejs/vite#4556
See  [issue comment]( https://github.com/vitejs/vite/issues/4556#issuecomment-898862114)  for details
> fix: normalize path(vitejs/vite#4556)

- packages/sprinkles/README.md
As of v1.1.0, this statement is no longer true.
> Sprinkles: Fix readme

- .changeset/eight-moons-lie.md
- fixtures/sprinkles/src/styles.css.ts
- packages/sprinkles/src/index.ts
- tests/E2E/__snapshots__/stylesheets.test.ts.snap
I realized I missed the `else` block where we handle the case where no `conditions` are provided in the atomic styles. This caused the css to compile incorrectly. This PR addresses that bug.
Use case:
```ts
const styleWithNoConditions = createAtomicStyles({
properties: {
color: {
red: {
vars: {
[alpha]: '1'
},
color: `rgba(255, 0, 0, ${alpha})`
}
}
}
});
```
> Sprinkles: Fix style object bug when no conditions are present

- README.md
Remove reference to deprecated function composeStyles from table of contents.
> Remove `composeStyles` from readme TOC

- README.md
- site/docs/styling-api.md
at the moment the "rotate" css properties have little browser support.
https://caniuse.com/?search=rotate
> Use `transform` property in docs instead of `rotate`

- package.json
- packages/recipes/package.json
- packages/sprinkles/package.json
- yarn.lock
The `*` peer dep was causing changesets to always release.
> Fix recipe and sprinkles peer deps

- .changeset/rare-lemons-study.md
- packages/recipes/src/index.ts
- packages/recipes/src/types.ts
- site/docs/recipes-api.md
- tests/recipes/recipes-type-tests.ts
Add `RecipeVariants` type to get variants from a recipe.
This type would help consumers easily get the variants type. Useful for typing their components:
```tsx
const textRecipes = recipe({
variants: {
size: {
small: { fontSize: '12px' },
medium: { fontSize: '16px' },
large: { fontSize: '24px' },
},
},
});
type TextVariants = RecipeVariants<typeof textRecipes>;
type Props = {
// ... other props
} & TextVariants;
function Text({ size, ...props }: Props) {
return <div {...props} className={textRecipes({ size })} />;
}
<Text size="small">Awesome text</Text>;
```
For more context, these types are easy to get from outside the lib using `Parameters`, but having these utilities would make it easy and provide an official way to get these, plus if the way to get the type changes, consumers won't …
> Add RecipeVariants type to get variants from recipes

- .changeset/flat-colts-cheer.md
- packages/babel-plugin/src/index.test.ts
- packages/babel-plugin/src/index.ts
> Handle pre-compiled `createTheme` destructuring in Babel plugin

- .changeset/ninety-pears-march.md
- packages/vite-plugin/src/index.ts
Strips out the trailing `?used` if it exists.
> Fix vite file path bug

- .changeset/calm-ravens-sit.md
- packages/vite-plugin/src/index.ts
Fixes #427 
Also see a different approach in this PR #457 
When used with Vite, if `*.css.ts` module is imported from _outside_ of the root directory, the following error occurs:
```
Unable to locate /path-to.css.ts$$$@scope/package-name in the CSS map.
```
This happens, because the path `../path-to.css.ts` gets overridden to `/../path-to.css.ts` (by `vite:import-analysis`) and then consequently to `/path-to.css.ts` (by `vite.normalizePath`). As a result, `cssMap` stores the source under a different key as it is being retrieved.
This is where the source is stored under `../path-to.css.ts$$$@scope/package-name`:
https://github.com/seek-oss/vanilla-extract/blob/076b02d91f22d0b61df2dd9edd875f86ac4a55ea/packages/vite-plugin/src/index.ts#L152
This is where the we are trying to retrieve the …
> Vite: Mark `.vanilla.js` and `.vanilla.css` modules as virtual.

- .changeset/tiny-brooms-guess.md
- package.json
- packages/css/src/vars.ts
- packages/private/src/types.ts
- yarn.lock
Not sure what TypeScript 4.5 is smoking but it seems to think that [template strings are records now](https://www.typescriptlang.org/play?ts=4.5.0-beta#code/C4TwDgpgBAKhC2YA2BDYEDKwBOBLAdgOZQC8UABgG4rYAUAtPQCQDeAzjgYQL4CU5AKFCQoAOQD22eCiRY8RUlADkbcfAj1qSAK4QlAoeGgBBfAHkARgCsIAY2CKASnckATADwd5xAD5R82vAWENgANFAo+CAAfADcBsIminCIqOhyXFAQAB7o+K5sUKaWNvZQAPzKAOowAGJKUABcymYA1iggSvGJUABCihJSMhkKOXkFRebWdg6VSjX1TS3tnbFAA)? I personally think this might be a TS bug but we can work around it.
Resolves #484
Resolves #483
> Fix theme contract types in TypeScript 4.5

- package.json
Yarn 3 infers the `--immutable` flag in CI environments. This prevents the version command from updating the lockfile for the version packages PR.
> Fix version script for yarn 3

- .changeset/config.json
Tests are a workspace now, which means that `"private": true` takes care of ignoring them.
> Don't ignore tests

- .changeset/flat-games-call.md
- package.json
- packages/css/package.json
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
- pnpm-lock.yaml
> Ensure identifiers are escaped properly

- .changeset/grumpy-carrots-arrive.md
- packages/css/package.json
- packages/dynamic/package.json
- packages/recipes/package.json
- packages/sprinkles/package.json
- packages/webpack-plugin/package.json
Fixes the following issue: https://github.com/markdalgleish/preconstruct-node-esm-import-issue. To see the fix working, you can run this repro locally and manually apply the diff seen in this PR to `node_modules/@vanilla-extract/sprinkles/package.json`.
Related issue on Preconstruct: https://github.com/preconstruct/preconstruct/issues/432
More detail about the `exports` field and its conditional syntax: https://webpack.js.org/guides/package-exports
I ran into this issue because the Sprinkles runtime was being consumed within an ESM package (i.e. `"type": "module"`) and Node.js doesn't allow directory imports in ESM mode. Instead, all nested import paths need to be explicitly defined in the `exports` field.
> Add `exports` field to packages with multiple entrypoints

- .changeset/odd-suits-call.md
- babel.config.js
When we started transpiling the browser based packages correctly, we stopped transpiling down to node 12 features for the node based packages.
There is a known issue with the webpack-plugin. Not sure about the other ones but will release just in case.
> Ensure code is compatible with node 12

- .changeset/itchy-eyes-protect.md
- packages/sprinkles/src/createUtils.ts
- tests/sprinkles/sprinkles-type-tests.ts
- tests/sprinkles/sprinkles.test.ts
Generic conditional values currently need to extend `string | number`. This PR also adds `boolean` so that values like `{ mobile: false, desktop: true }` are supported.
> Sprinkles: Support boolean conditional values

- .changeset/friendly-turkeys-play.md
- packages/integration/src/processVanillaFile.ts
- packages/integration/src/virtualFile.ts
- packages/webpack-plugin/package.json
- packages/webpack-plugin/src/loader.ts
- packages/webpack-plugin/src/virtual.ts
- packages/webpack-plugin/virtual/package.json
- pnpm-lock.yaml
This also removes the dependency on the virtual-resource-loader and moves it internally for colocating compression code.
Resolves #374
> Compress CSS resources to keep the virtual size down

- .changeset/cold-bags-jump.md
- packages/integration/package.json
- pnpm-lock.yaml
Pinning the `eval` dependency on the `@vanilla-extract/integration` package as a quick fix for #637 
Fixes https://github.com/seek-oss/vanilla-extract/issues/637
> integration: Fix __webpack_require__ is not defined error

- .changeset/moody-poems-tan.md
- packages/css/package.json
- packages/css/src/transformCss.ts
- packages/css/src/validateMediaQuery.test.ts
- packages/css/src/validateMediaQuery.ts
- pnpm-lock.yaml
This PR adds some basic CSS media query linting (see: https://github.com/seek-oss/vanilla-extract/discussions/480).
At work, we've shipped a couple of bugs because an invalid media query wasn't caught during code review (eg. `@media (max-width: 600px`). CSSType doesn't catch this, nor does Vanilla Extract. It [looks like CSSType might tackle it in the future](https://github.com/frenic/csstype/issues/66#issuecomment-1004090875).
I wanted to see if I could put something quick together this weekend so this is that attempt. I also tried doing a RegEx attempt but that ended up getting pretty unwieldy (similar to this: https://github.com/niksy/regex-css-media-query).
Would love to hear if you had any ideas on how to tackle this!
> feat: validate media queries

- site/src/themes.css.ts
The CSS endpoint now generates `ml` instead of `MonoLisa` to avoid conflicts with local fonts
> Fix fontFamily since it changed in the CSS file

- .changeset/twenty-crabs-boil.md
- packages/integration/src/addFileScope.test.ts
- packages/integration/src/addFileScope.ts
- packages/integration/src/compile.ts
- packages/integration/src/processVanillaFile.ts
- packages/rollup-plugin/test/__snapshots__/rollup-plugin.test.ts.snap
- packages/vite-plugin/src/index.ts
- packages/webpack-plugin/src/loader.ts
- tests/stylesheets/__snapshots__/features.test.ts.snap
- tests/stylesheets/__snapshots__/recipes.test.ts.snap
- tests/stylesheets/__snapshots__/sprinkles.test.ts.snap
- tests/stylesheets/__snapshots__/themed.test.ts.snap
- tests/stylesheets/__snapshots__/unused-modules.test.ts.snap
> Salt identifier hashes with package name

- packages/rollup-plugin/test/__snapshots__/rollup-plugin.test.ts.snap
- packages/rollup-plugin/test/rollup-plugin.test.ts
- site/docs/setup.md
- The package name is not needed anymore after https://github.com/seek-oss/vanilla-extract/pull/673
- The test actually wasn't testing what I intended (preserving modules with correct paths for both JS and CSS – `preserveModuelsRoot` is normally not required but required here because of the way the fixture is referenced)
This has no effect on any published package code, so I didn't add a changeset.
> Fix rollup plugin tests and docs for preserve modules with adjusted asset names

- .changeset/slow-turkeys-shout.md
- packages/rollup-plugin/src/index.ts
Fixes #691
The issue was that `emittedFiles` still held references to the assets from the previous build. Those are accessed down below at `if (!emittedFiles.get(fileName))`. However, assets get cleared on a re-build, so we need to re-emit those files when we're in watch mode.
I wish I could write a test for this but I have no idea how to simulate rollup watch mode and file changes :/
> rollup: clear emitted files cache for watch mode

- .changeset/fuzzy-flowers-fold.md
- packages/vite-plugin/src/index.ts
In the event of a dev server being present, currently this is treated as though we're in dev mode. But in some cases (as in Nuxt's) the server is present in the build process and we can detect this by looking to see whether `isProduction` is set.
resolves #445, resolves #446
> fix(vite-plugin): return css in production

- .changeset/silly-yaks-whisper.md
- .changeset/soft-lobsters-promise.md
- packages/vite-plugin/src/index.ts
Hi! We are trying to support `vanilla-extract` in [`@shopify/hydrogen`](https://github.com/shopify/hydrogen) but we've found that the Vite plugin in this repo is not compatible with React Server Components.
I'm adding here some minimal changes that enable RSC support with the [plugin we are making here](https://github.com/facebook/react/pull/22952). Forking your plugin is also possible, if for any reason you don't want to support RSC yet.
- The first commit is, to my understanding, a bug fix. Vite uses sometimes `?v=42`-like query strings, and I think the regex checked in https://github.com/seek-oss/vanilla-extract/commit/0bc2b9fd4bf96e9cfef87b656ed225f9dae2c815 should pass regardless.
- The second commit adds an environment variable that is truthy when we do an RSC build. The main …
> Support React Server Components in Vite plugin and fix HMR

- .changeset/unitless-scale.md
- packages/css/src/transformCss.ts
I've noticed the following CSS is being generated when I set `scale: 1`:
Scale [doesn't accept px](https://developer.mozilla.org/en-US/docs/Web/CSS/scale), so I think it should be added to the list of unitless properties.
> Add scale to the list of unitless properties

- README.md
- site/legacy-routes.json
- site/src/App.tsx
- site/src/Code/CompiledCode.css.ts
- site/src/Code/CompiledCode.tsx
- site/src/HomePage/HomePage.tsx
- site/webpack.config.js
Some post-update site fixes:
- Add handling for legacy routes
- Hide `Show Output` button on mobile when no output to show
- Fix horizontal page scroll caused by code panels
- Make code panel max heights shorter on short screens
> Site redirects and bugs

- site/docs/integrations/gatsby.md
Hi!
I've added the needed `peerDeps` to the instructions because the Gatsby plugin doesn't install them for the user.
> chore(docs): Correct peerDeps for Gatsby integration

- .changeset/brown-rice-draw.md
- packages/css/src/style.ts
```ts
const vars = createThemeContract({
info: {
bgColor: null,
},
warn: {
bgColor: null,
},
success: {
bgColor: null,
},
error: {
bgColor: null,
}
});
export const staticCardStyles = styleVariants(
vars,
({bgColor}) => [staticCard, { backgroundColor: bgColor }]
);
```
the error in my components lib is:
> Property 'bgColor' does not exist on type '`var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})` | MapLeafNodes<{ info: { bgColor: null; }; warn: { bgColor: null; }; success: { bgColor: null; }; error: { bgColor: null; }; }[Key], CSSVarFunction>'.ts(2339)
when i fix the styleVariants's type, it's works well.
```ts
const vars = createThemeContract({
info: {
bgColor: null,
},
warn: {
bgColor: null,
},
success: {
bgColor: null,
},
error: {
bgColor: null,
}
}); …
```
> Fix `styleVariants` type when using the map data function

- site/docs/overview/theming.md
- site/docs/packages/dynamic.md
The name of the Container argument in the documentation seems to be wrong, so it has been corrected.
> [Fix Document] Fix wrong props name

- .changeset/gold-trainers-sing.md
- .changeset/hungry-ties-judge.md
- .changeset/popular-seas-relate.md
- packages/css/src/identifier.test.ts
- packages/css/src/identifier.ts
- packages/css/src/vars.ts
I was getting errors during development when my variable names contained spaces. Turns out it's because we weren't handling variable identifiers the same as everything else, instead manually reimplementing the `generateIdentifier` logic but forgetting to replace spaces with underscores.
To fix this, I've refactored `createVar` to use `generateIdentifier`, but since var debug names previously didn't have the file name prefix applied, I've also added an additional option to `generateIdentifier` to support turning this off, which `createVar` then uses. This is public API so I've added a changeset for it.
NOTE: This PR now includes a bonus fix, ensuring debug file names are present for `.cjs` and `.mjs` files.
> Use standard identifier generation logic for variable names

- .changeset/chilled-pets-help.md
- packages/vite-plugin/src/index.ts
Turns out we can use the same approach for [SolidStart](https://github.com/solidjs/solid-start) that was used for Astro since they're both managing CSS during SSR in a similar way.
> Add experimental support for SolidStart to Vite plugin

- .changeset/twelve-avocados-provide.md
- packages/css/adapter/package.json
- packages/css/disableRuntimeStyles/package.json
- packages/css/fileScope/package.json
- packages/css/functionSerializer/package.json
- packages/css/injectStyles/package.json
- packages/css/recipe/package.json
- packages/css/transformCss/package.json
This PR gets .css.ts files working in the Vitest test runner. WIthout the `exports` definitions, Vitest was (stragely) resolving the ESM version of `@vanilla-extract/css` but the CJS version of `@vanilla-extract/css/fileScope`, causing filescope errors.
> Fix entrypoint resolving in Vitest

- .changeset/ninety-windows-marry.md
- packages/css/package.json
- packages/css/src/ahocorasick.d.ts
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
- pnpm-lock.yaml
When creating `.css.ts` files with large amounts of locally scoped classes, commonly encountered when using sprinkles, CSS output could be slow to create due to how selectors are transformed with large dynamic regular expressions. This issue was especially prevalent on M1 Macs. 
To resolve this, the old regular expression approach has been removed in favour of the following:
- In most cases, the selector being processed is just a single classname reference. In this case we don't need to search for all known local classnames and can be transformed whole after a single Map lookup. 
- In more complicated selectors, the RegExp approach has been removed in favour of using an Aho-Corasick based search, which is ideal for searching for multiple different keywords in text. 
-  There aren't many …
> Improve performance of transformCss with large amounts of class names

- .changeset/spicy-planes-approve.md
- packages/next-plugin/src/index.js
The actual issue this solves was because the Next server build was marking the virtual CSS files as external, which means a standard node require is used, obviously failing. While this is strange more of a Next issue, we shouldn't be generating CSS in the server build anyway. 
Resolves #569
> Don't output CSS on Next server builds

- .changeset/lovely-lies-hide.md
- packages/integration/src/transform.ts
Currently both transforms are synchronous because the Babel `transform` method used is just an alias for `transformSync` — see [here][1] and [here][2].
[2]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/babel__core/index.d.ts#L398-L401
[1]: https://github.com/babel/babel/blob/main/packages/babel-core/src/transform.ts#L63-L72
> Use async Babel transform in `integration/transform.ts`

- .changeset/tasty-olives-tell.md
- packages/recipes/src/index.ts
Closes #739
"Partial" builds (simple tsc builds, no bundling) will emit wrong declaration when using recipes. This allows it to use the correct import.
> Add RuntimeFn as an export to recipes index

- .changeset/loud-parrots-perform.md
- packages/css/package.json
- pnpm-lock.yaml
Bumps [@emotion/hash](https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fhash%400.9.0) dependency to 0.9.0.
This `@emotion/hash` version adds an `exports` fields in its `package.json` file and fixes a Nuxt SSR build error:
```
[nuxt] [request error] [unhandled] [500] hash is not a function
```
> bump @emotion/hash dependency from 0.8.0 to 0.9.0

- site/src/render.tsx
Since moving to GitHub Actions the change in environment variables left the open graph images rendering with dev urls in production.
> site: Fix open graph image urls

- site/docs/integrations/rollup.md
- `assetFileNames` only exists inside `output`: https://rollupjs.org/configuration-options/#output-assetfilenames
- `preserveModules` exists in both top-level and in `output`, but the top-level one is deprecated: https://rollupjs.org/configuration-options/#output-preservemodules
> docs: fix rollup configuration

- .changeset/empty-snakes-deny.md
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
> Transform `content` property values inside `@keyframes` rules

- .changeset/empty-snakes-deny.md
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
Adding a `transformProperties` method that wraps `transformContent` and `pixelifyProperties`. Applying this to `@keyframes` rules as well to make it consistent with the other rules (missed this in #990).
> Add transform wrapper method, use it for `@keyframes` rules

- .changeset/shy-beers-pull.md
- packages/vite-plugin/src/index.ts
- site/docs/integrations/vite.md
Provides the ability to opt in to emitting CSS during SSR.
```js
// vite.config.js
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
export default {
plugins: [
vanillaExtractPlugin({
emitCssInSsr: true
})
]
};
```
> vite: Add `emitCssInSsr` option

- site/src/mdx-components.tsx
Adding the `name` attribute to headings on the site in the hope that the elements can be picked up by the search indexer and support linking to hashes.
See [docs](https://docsearch.algolia.com/docs/tips/#add-anchors-to-headings).
> site: Add `name` attributes to Headings

- .changeset/old-avocados-play.md
- .github/workflows/validate.yml
- packages/babel-plugin-debug-ids/src/index.ts
Fixes `args.at is not a function` error when using the `babel-plugin-debug-ids` package in node 14. Refactored the argument traversal to ensure backwards compatibility.
Also setup CI to run on minimum supported version of node to catch this category of problem going forwards.
> Fix babel plugin in node14, run ci on supported node versions

- site/contents.js
- site/docs/api/add-function-serializer.md
- site/docs/packages/recipes.md
- site/docs/packages/sprinkles.md
I'm excited to finally get this documented! Keen to get feedback on it though.
I'm not sure where this should go from an IA perspective, so I've added it to the end of "API" for now. I originally added it further down the nav under an "Advanced API" section, but then I felt like that was a bit too hidden, so I don't know 🤷‍♂️
> Add docs for `addFunctionSerializer`

- pnpm-lock.yaml
- site/package.json
- site/src/DocsPage/DocsPage.tsx
- site/src/Fab/Fab.css.ts
- site/src/HomePage/HomePage.css.ts
- site/src/HomePage/HomePage.tsx
- site/src/SearchInput/SearchInput.css.ts
- site/src/SearchInput/SearchInput.tsx
- site/src/mdx-components.tsx
- site/src/themeUtils.ts
- site/src/themes.css.ts
- site/webpack.config.js
[**Preview site**](https://63fc30f6771c470d7338fad6--vanilla-extract-css.netlify.app)
Created a `SearchInput` component that wraps algolia's `DocSearch` component.
Not customizing too much for now, the two notable customizations are:
- Making search result URLs relative rather than absolute so clicking a search result when running the site locally/on a preview site doesn't take you to production
- Customizing the missing result URL to point to a github issue template
[DocSearch component API Reference](https://docsearch.algolia.com/docs/api)
I've also taken a crack at the styling and general positioning on site. I've put it next to the color mode icon/fab, and attempted to style it in the same manor as the fab, mainly for consistency. Feel free to clean up or change the styles completely, …
> site: Add search

- .changeset/shiny-socks-lick.md
- packages/integration/src/processVanillaFile.test.ts
- packages/integration/src/processVanillaFile.ts
The `eval` result we use to serialize modules is an object containing the module's exports, so its order can't be reliably depended on. This was resulting in module exports sometimes being serialized in the wrong order. In [my reproduction](https://github.com/askoufis/vanilla-extract-issue-1027-repro), the effect of this was `createSprinkles` being called on a variable that was declared on the line below, causing a runtime error.
```js
import "/src/App.css.ts.vanilla.js";
import { createSprinkles as _ad221 } from "/node_modules/.vite/deps/@vanilla-extract_sprinkles_createRuntimeSprinkles.js?v=0be76525";
// Referencing `textProperties` before it's defined
export var textAtoms = _ad221(textProperties);
export var textProperties = { /* */ };
```
We can take advantage of [the new exports …
> integration: Sort serialized module exports

- .changeset/mighty-carpets-breathe.md
- packages/recipes/src/createRuntimeFn.ts
- packages/recipes/src/types.ts
- tests/recipes/recipes-type-tests.ts
- tests/recipes/recipes.test.ts
Adds variants function to a recipe's runtimeFn.
This is a continuation of #712.
> Expose variants from recipe

- .changeset/good-cats-boil.md
- packages/next-plugin/src/index.ts
Next plugin doesn't currently have `d.ts` file. So user can't use intellisense for options. This PR provides that.
> next-plugin: add types to plugin config

- .changeset/sprinkles-layers.md
- fixtures/sprinkles/src/styles.css.ts
- packages/sprinkles/src/index.ts
- site/docs/packages/sprinkles.md
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-esbuild--development.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-esbuild--production.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-esbuild-next--development.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-esbuild-next--production.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-mini-css-extract--development.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-mini-css-extract--production.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-parcel--development.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-parcel--production.css
- tests/e2e/sprinkles.playwright.ts-snapshots/sprinkles-vite--production.css
This PR adds an optional `@layer` property to the options passed to `defineProperties`.
Example usage:
```ts
// sprinkles.css.ts
import { defineProperties } from '@vanilla-extract/sprinkles';
import { layer } from '@vanilla-extract/css';
export const sprinklesLayer = layer();
const properties = defineProperties({
'@layer': sprinklesLayer,
// etc.
});
```
> sprinkles: Add support for layers

- .changeset/healthy-turtles-help.md
- packages/rollup-plugin/src/index.ts
I have changed the asset emitting logic significantly.
Before, we emitted css assets in the `resolveId` stage and kept track of emitted assets in a plugin-local variable (`emittedFiles`), clearing them all on a rebuild. However, emitted css assets are external and not part of the module graph and thus not cached by rollup. Previously emitted assets are cleared on rebuilds and we didn't re-emit them (because on rebuild only the changed files get transformed/resolved).
I changed this to use the rollup caching mechanism by attaching the css output to the module's `meta` during `resolveId` and only emitting the actual css assets in the `moduleParsed` stage. Module info is cached between rebuilds, so this way we can access previous build outputs.
Fixes: #1076
(Also a better fix for #691. What …
> rollup-plugin: fix caching in watch mode

- .changeset/popular-kings-rhyme.md
- packages/babel-plugin-debug-ids/src/index.test.ts
- packages/babel-plugin-debug-ids/src/index.ts
Fixes #935.
Adds logic to handle the extra 2 cases mentioned in the issue. Tested against [the reproduction](https://github.com/zbauman3/demos/tree/vanilla-extract-next-dev).
> Handle alternative compiled forms of array destructured `createTheme`

- .changeset/pink-students-grab.md
- packages/vite-plugin/src/index.ts
According [to Vite docs](https://vitejs.dev/guide/api-plugin.html#path-normalization), resolved ids will have `/` as directory separators.
But `watchFiles`, returned by the `compile` function, have platform-specific directory separators (`\` in Windows), so comparing file and module id (`file === validId`) will always be false in Windows and module itself will be added to watched files (which breaks HMR and leads to page reload).
So, by normalizing paths from `watchFiles` (using POSIX directory separators instead of platform-specific), module will be correctly ignored from adding to watched files and HMR will work.
> fix(vite-plugin): Fix HMR in Windows

- .changeset/shiny-crews-rescue.md
- packages/next-plugin/src/index.ts
Currently we're getting experimental flags (such as `appDir`) from the user config, `nextConfig`. This PR changes it to use the `options.config` argument of the `webpack` function instead. It's similar to `nextConfig` but it has all fallback values resolved as `appDir` now defaults to `true`.
Fixes #1087.
> Use the resolved Next.js config in `next-plugin`

- site/docs/integrations/rollup.md
- site/docs/integrations/vite.md
While looking into #1111 I realized that the `esbuildOptions` config exposed by the esbuild, vite and rollup plugins is only documented for the esbuild plugin. I've copy-pasted the same docs to the vite and rollup integration pages.
> Document `esbuildOptions` in vite and rollup integration docs

- .changeset/twenty-tables-report.md
- packages/sprinkles/src/index.ts
As discussed on Discord, exposing the `SprinklesProperties` type allows wrapping `createSprinkles` with custom utilities without resorting to awkward workarounds like:
```ts
type VarargParameters<T> = T extends (args: infer P) => any ? P : never;
type SprinklesProperties = VarargParameters<typeof createSprinkles>;
```
which it turns out are also very expensive for tsc to compute (I personally had compile times to skyrocket in a library I maintain).
> feat: export SprinklesProperties type

- .changeset/fontFace-array.md
- packages/css/src/style.ts
- packages/css/src/transformCss.test.ts
- site/docs/api/font-face.md
This PR adds support to the `fontFace` function to accept an array of font face rules that share the same font family name.
Example usage:
```
// text.css.ts
import { fontFace, style } from '@vanilla-extract/css';
const gentium = fontFace([
{
src: 'local("Gentium")',
fontWeight: 'normal',
},
{
src: 'local("Gentium Bold")',
fontWeight: 'bold',
},
]);
export const font = style({
fontFamily: gentium,
});
// CSS
@font-face {
src: local("Gentium");
font-weight: normal;
font-family: "text_gentium__fih47p0";
}
@font-face {
src: local("Gentium Bold");
font-weight: bold;
font-family: "text_gentium__fih47p0";
}
.text_font__fih47p1 {
font-family: "text_gentium__fih47p0";
}
```
> Allow `fontFace` to accept array of font face rules

- .changeset/wild-starfishes-melt.md
- packages/next-plugin/src/index.ts
> Fix error when intializing next plugin

- .changeset/calm-starfishes-smell.md
- packages/next-plugin/src/index.ts
Fixes #1154, adds parity with next for the css-loader `url` and `import` options, by leveraging next's logic.
> fix(next-plugin): url statements in vanilla css would not respect next's setup for resolving assets

- .changeset/curly-lies-flash.md
- packages/css/src/identifier.test.ts
- packages/css/src/identifier.ts
- packages/css/src/types.ts
- site/docs/integrations/esbuild.md
- site/docs/integrations/next.md
- site/docs/integrations/rollup.md
- site/docs/integrations/vite.md
- site/docs/integrations/webpack.md
Hello, I am submitting a request to reopen Pull Request #657. This proposed enhancement aims to unlock my team, which is currently facing a classname clash issue, we are using multiple micro-frontends within a host application. Unfortunately, some of the generated hash values from these micro-frontends coincide with hash values from the host application. We are really hoping for this feature to be integrated, like that it will allows us to customize the generated classnames by applying prefixes specific to each micro-frontend and will guarantee the uniqueness of every hash.
Moreover, the implementation of this feature could help multiple persons with similar scenarios and other challenges, we can found in the following discussion:
- …
> Allow custom identifier hashing

- .changeset/silver-singers-bathe.md
- packages/integration/package.json
- packages/integration/src/processVanillaFile.test.ts
- packages/integration/src/processVanillaFile.ts
- pnpm-lock.yaml
- site/package.json
The `eval` package has caused issues [in the past](https://github.com/vanilla-extract-css/vanilla-extract/issues/637) that resulted in [pinning its version](https://github.com/vanilla-extract-css/vanilla-extract/pull/639/files#diff-62f6906083a84673a05063f208cfe697e0134acee3dded6930bab0d43f0789dfR19). At roughly the same time, `0.1.8` was released but we didn't update. `0.1.8` [fixes some issues](https://github.com/pierrec/node-eval/commits/master) we've run into with Node globals, and given its stability over the last ~1 year I think it's safe to update.
> Bump `eval` to `0.1.8` to fix missing Node globals issues

- packages/css/package.json
- packages/css/src/transformCss.ts
- pnpm-lock.yaml
The existing `ahocorasick` package doesn't export anything which can cause issues with certain frameworks. The `modern-ahocorasick` package has the same API as the old one but actually exports something instead of adding to the global namespace.
> Use modern-ahocorasick

- .github/workflows/release.yml
Not sure why but [`main` doesn't seem to work](https://github.com/vanilla-extract-css/vanilla-extract/actions/runs/6807432494/job/18510438611#step:6:13).
> Pin `changesets/action` to `v1`

- .changeset/new-kangaroos-punch.md
Changesets doesn't like any release that's not `major`/`minor`/`patch`, and it gives you an unhelpful error if that happens. [I wrote the bad changeset though](https://github.com/vanilla-extract-css/vanilla-extract/pull/1207/commits/196e180971be9678456d9799afe56820371c552a) 😅.
> Fix changeset release type

- .changeset/tasty-ducks-try.md
- packages/vite-plugin/package.json
- pnpm-lock.yaml
Discovered by @hi-ogawa here https://github.com/remix-run/remix/pull/8000#discussion_r1392440996
> Bump `postcss-load-config` to be able to load PostCSS configs defined as ES Modules

- .changeset/loud-laws-poke.md
- packages/esbuild-plugin-next/package.json
- packages/esbuild-plugin/package.json
Prior art and discussions: https://github.com/vanilla-extract-css/vanilla-extract/pull/1018, https://github.com/vanilla-extract-css/vanilla-extract/pull/1171
`esbuild` is now a peer dependency in `esbuild-plugin` and `esbuild-plugin-next`.
Why make it a peer dependency? Because our script to bundle types bundles the `Plugin` type from `esbuild` into the output, which can cause a type error when consumers try to use it.
It's [marked as optional](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta), so it won't crash on install when consumers don't have `esbuild` in their dependencies.
I believe this is a better solution than both #1018 and #1171.
#1171 is too intrusive and adds `esbuild` everywhere, and consumers have to include it in their dependencies. …
> Make `esbuild` an optional peer dependency

- .changeset/proud-months-tell.md
- packages/vite-plugin/src/index.ts
This flag needed to be enabled in the Remix Vite plugin test suite in order for it to pass when using VE, so this PR adds Remix to the ever growing list of frameworks that need this feature enabled. This seems to be a sign that this should maybe be the default, but since that's likely to be considered a breaking change, it makes sense that this could go through as a non-breaking fix in the meantime.
> Default `emitCssInSsr` if Remix plugin is present

- .changeset/great-geckos-marry.md
- packages/vite-plugin/src/index.ts
Currently the CSS code that was processed with PostCSS (`cssSource`) is written to the `cssMap` cache:
https://github.com/vanilla-extract-css/vanilla-extract/blob/27552826716993d9923d2aa5f30513594ff3c1ee/packages/vite-plugin/src/index.ts#L241
However, the invalidation uses the source code that was not processed by PostCSS (`source`):
https://github.com/vanilla-extract-css/vanilla-extract/blob/27552826716993d9923d2aa5f30513594ff3c1ee/packages/vite-plugin/src/index.ts#L217
This results in unnecessary invalidation of those modules that may not have changed.
> fix(vite-plugin): prevent extra style module invalidations when using PostCSS

- .changeset/brown-timers-hang.md
- .changeset/spotty-suits-hide.md
- .changeset/tricky-games-lick.md
- babel.config.js
- package.json
- packages/integration/package.json
- packages/vite-plugin/src/index.ts
- pnpm-lock.yaml
- site/babel.config.js
- site/webpack.config.js
- test-helpers/src/startFixture/esbuild.ts
- test-helpers/src/startFixture/webpack.ts
Fixes https://github.com/vanilla-extract-css/vanilla-extract/issues/1236
- Update Babel config to target Node.js 14
- Configure Preconstruct to retain `await import('vite')` syntax
- Upgrade Vite, Vitest and vite-node
Previously, we were using the [`esmodules` target](https://babeljs.io/docs/options#targetsesmodules) which targets the very first versions of browsers that support ES Modules. That includes a lot of transforms that we don't need to run anymore. Related PR: https://github.com/vanilla-extract-css/vanilla-extract/pull/520
How Babel targets changed after tweaking the Babel config:
<details>
<summary>Before</summary>
```
Using targets:
{
"android": "61",
"chrome": "61",
"edge": "16",
"firefox": "60",
"ios": "10.3",
"node": "13.2",
"opera": "48",
"safari": "10.1",
"samsung": "8.2" …
```
> Update Babel config to target modern browsers/Node.js

- site/contents.js
- site/docs/integrations/remix.md
Per https://github.com/vanilla-extract-css/vanilla-extract/discussions/1266#discussioncomment-8214117, just links to the Remix docs off-site and the Vite docs on-site.
I'm not sold on the phrasing of the page but figured I'd just ask for help. 😄
> docs: add Remix integration page

- .changeset/silly-seahorses-tickle.md
- packages/esbuild-plugin-next/package.json
- packages/esbuild-plugin/package.json
- packages/parcel-transformer/package.json
- packages/rollup-plugin/package.json
- packages/vite-plugin/package.json
- packages/webpack-plugin/package.json
- pnpm-lock.yaml
As per https://github.com/vanilla-extract-css/vanilla-extract/pull/1160#discussion_r1296699881, we should have included every plugin affected by #1252 and #1273.
> Update dependency `@vanilla-extract/integration`

- .changeset/clean-wolves-attend.md
- packages/rollup-plugin/package.json
Spinning up this PR from https://github.com/vanilla-extract-css/vanilla-extract/discussions/1289.
@mrm007 I don't know exactly what to test/verify for this change though. 
Heres the breaking changes from 3.x.x to 4.x.x: https://github.com/rollup/rollup/releases/tag/v4.0.0
I've done a quick scan, and it seems theres a few references to `preserveModules` in a test, which I am unsure if might cause errors down the line if the peer dependency is on `4.x.x` due to the breaking change note:
```
inlineDynamicImports, manualChunks and preserveModules have been removed on input option level: Please use the corresponding output options of the same names (https://github.com/rollup/rollup/pull/5143)
```
Other than that it looks to me this should be safe. 
Anything else we need to verify for this?
> Allow rollup@4.x.x as peer dependency

- .changeset/rude-toys-thank.md
- packages/vite-plugin/src/index.ts
Fixes #1295.
In the `configResolved` hook the `config.inlineConfig` object doesn't actually contain the user's config, so we need to grab in in the `config` hook.
> Correctly resolve the user's configured Vite plugins

- .changeset/clever-walls-cross.md
- packages/vite-plugin/src/index.ts
Fixes #1298.
Vitest adds [its own plugins](https://github.com/vitest-dev/vitest/blob/c2cceebbfd28f50c32b9ed6f4519b1fba96171b4/packages/vitest/src/node/plugins/index.ts#L202-L211) before our `config` hook gets a chance to run, so we need to filter them out before passing plugins to the compiler.
> Skip loading plugins added by Vitest

- .changeset/eleven-oranges-collect.md
Should've been included in https://github.com/vanilla-extract-css/vanilla-extract/pull/1247.
> Add next plugin to changeset

- .changeset/vite-plugin-remix.md
- packages/vite-plugin/src/index.ts
Similar to #1300, we need to filter out Remix before passing plugins to the compiler. 
[Remix throws an error](https://github.com/remix-run/remix/blob/f0688dd49f41e4bcdf8bc689a8380c2e0ee5c760/packages/remix-dev/vite/plugin.ts#L966-L970) if it's loaded without a config file, like we do when we initialise the vite-node compiler.
This has been an issue with version 4.x of our Vite plugin since the very beginning. https://github.com/remix-run/remix/pull/7990 was merged long before we released [v4.0.0](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract/vite-plugin%404.0.0).
> Don't pass Remix Vite plugin to the vite-node compiler

- .changeset/integration-plugins.md
- .changeset/vite-plugin-plugins.md
- packages/integration/src/compiler.ts
- packages/vite-plugin/src/index.ts
- playwright.config.ts
- test-helpers/src/startFixture/vite.ts
Fixes #1313.
This is similar to the fix provided by @hi-ogawa in https://github.com/remix-run/remix/pull/7990.
I believe this is a better fix than #1300 ~~and #1308~~ (see note below). 
Now that we load a new copy of the Vite config, we don't have to worry about filtering plugins before passing them to the vite-node compiler, since they don't share any state with the app's Vite config. 
Edit: We still need to filter out Remix because the plugins are incompatible **with and without** a config file.
> Load a new Vite config object for the vite-node compiler

- site/docs/packages/recipes.md
- site/docs/packages/sprinkles.md
On the pages explaining recipes and sprinkles, the link to the function serialization API results in a 404, because it points to `../../api` instead of `../api`.
> Fix link to function serialization API in the docs

- .changeset/weak-cherries-beg.md
- packages/recipes/src/types.ts
As per https://www.totaltypescript.com/concepts/the-prettify-helper
**Before:**
**After:**
> Improve type hint of recipe's runtime fn

- .changeset/hungry-berries-deliver.md
- packages/vite-plugin/src/index.ts
Related: https://github.com/dai-shi/waku/pull/559
> vite: Create compiler during `buildStart` instead of `configResolved`

- site/docs/api/add-function-serializer.md
- site/docs/packages/recipes.md
- site/docs/packages/sprinkles.md
Relative path syntax is a bit weird, and was causing some links to point to nowhere. Seems like we use absolute paths everywhere else in the docs, and they're easier to understand too IMO, so this PR fixes some broken links by converting them to absolute paths.
Fixes #1350.
Also fixes some other links that were broken.
> docs: Fix broken links

- .changeset/eight-peas-provide.md
- packages/vite-plugin/src/index.ts
We were incorrectly splitting the path inside `getAbsoluteId` on Windows because `path.sep` is OS-specific. We can use the static `path.posix.sep` instead because vite will always give us [normalized paths](https://vitejs.dev/guide/api-plugin#path-normalization).
Fixes #1339.
Fixes #1344.
> vite: Fix `.css.ts` file resolution on Windows

- .changeset/honest-pugs-tap.md
- fixtures/features/src/html.ts
- fixtures/features/src/index.ts
- fixtures/next-app-router/src/app/features/page.tsx
- fixtures/next-app-router/src/app/sprinkles/page.tsx
- fixtures/next-pages-router/src/pages/features/index.tsx
- fixtures/next-pages-router/src/pages/sprinkles/index.tsx
- fixtures/sprinkles/src/html.ts
- fixtures/sprinkles/src/index.ts
- packages/next-plugin/src/index.ts
- test-helpers/src/startFixture/next.ts
- tests/e2e/fixtures-next-development.playwright.ts
- always output css
- fixes a bug with composed selector global css class not being applied in SSR with pages router
- use `next-style-loader` for pages router in development (as per original comment, next-style-loader can mess up css order in development mode, but this is surely better than no css at all.)
- fixes a bug with new page styles not being added to the document when client side routing https://github.com/vanilla-extract-css/vanilla-extract/issues/1152
- remove appDir config check
Didn't want to add them all, as it would increase the workflow time quite a bit.
I think the ones I've added are enough to validate the fixes.
Not sure if we want to change all the fixtures to have a separate `html.ts` for consistency.
> fix: Next plugin - pages router style loading

- .changeset/hip-zebras-hear.md
- packages/vite-plugin/src/index.ts
Fixes #1329.
Explained in a bit more detail [here](https://github.com/vanilla-extract-css/vanilla-extract/issues/1329#issuecomment-1963925841).
> Filter all Remix vite plugins before passing to `vite-node`

- .changeset/chilly-hairs-serve.md
- .changeset/rare-days-suffer.md
- .changeset/warm-bulldogs-sin.md
- packages/private/src/walkObject.ts
- pnpm-lock.yaml
- tests/package.json
- tests/walkObject/tokens.ts
- tests/walkObject/walkObject.vitest.test.ts
Fixes #1360.
`walkObject` doesn't work on module namespace objects when running inside `vite-node`. This is because [module namespace objects don't have a `constructor` function](https://262.ecma-international.org/6.0/#sec-module-namespace-objects).
This "bug" has gone unnoticed for a long time because `esbuild` was modifying the export in some way that made it work, but `vite-node` doesn't seem to do this.
I don't think we need to use `constructor` anymore since `walkObject` is constrained to only work on objects, at least as far as the type signature is concerned.
> Fix `walkObject` to work with module namespace objects

- .changeset/chilly-hairs-serve.md
- .changeset/rare-days-suffer.md
- .changeset/soft-weeks-confess.md
Updating some changesets, and adding one for `@vanilla-extract/integration` so the fix in `@vanilla-extract/private` will make it all the way to the vite plugin release.
> Update and add changeset

- docs/treat-migration-guide.md
Going through the process of properly deprecating and archiving [treat](https://github.com/seek-oss/treat), realised that we should probably link to the migration guide just in case. 
Updating the guide to remove the bit about the babel plugin as users no longer need to install it.
> Remove reference to babel plugin from treat migration guide

- .changeset/eighty-shirts-lie.md
- packages/css/src/style.ts
- site/docs/global-api/global-font-face.md
This PR adds support to `globalFontFace` function to accept an array of font face rules.
example:
```ts
import {
globalFontFace,
style
} from '@vanilla-extract/css';
const gentium = 'GlobalGentium';
globalFontFace(gentium, [
{
src: 'local("Gentium")',
fontWeight: 'normal'
},
{
src: 'local("Gentium Bold")',
fontWeight: 'bold'
}
]);
export const font = style({
fontFamily: gentium
});
```
If you need any additional documentation or clarification, please let me know.
Thank you!
> feat: allow `globalFontFace` to accept array of font face rules

- .changeset/gentle-ligers-act.md
- packages/vite-plugin/src/index.ts
Fixes #1351.
Fixes #1372.
Thanks to @szszoke for the [lead](https://github.com/vanilla-extract-css/vanilla-extract/issues/1351#issuecomment-2082422153).
Snapshot version: `0.0.0-fix-watch-mode-20240429115131`.
While it would be nice to have some kind of fixture/integration test for vite watch mode, it would be a bit involved, so I'd prefer to ship the fix first, and look into a test later.
I wonder if this also addresses the issue that prompted #1327.
> vite: Fix CSS output not updating in watch mode

- .changeset/odd-crews-itch.md
- packages/vite-plugin/src/index.ts
This change was meant to be included in #1397.
> vite: Ensure compiler is re-used between builds

- .github/workflows/validate.yml
- playwright.config.ts
- Retry test failures on CI. Should help with flakey tests.
- Forbid `.only` on CI (fail the build)
- Update a github action version to fix a deprecation warning
> test, ci: Playwright config tweaks, update action versions

- .changeset/clean-tigers-drive.md
- .changeset/silver-cows-march.md
- packages/css/package.json
- packages/integration/package.json
- packages/integration/src/addFileScope.test.ts
- packages/integration/src/addFileScope.ts
- pnpm-lock.yaml
- site/package.json
Fixes #1405.
TL;DR: multi-line strings with literal newlines were being manged by `dedent` (ultimately because of SWC, see extra notes below).
These used to be correctly dedented by `outdent` in `@vanilla-extract/integration@7.1.2`, but [since swapping to `dedent`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fintegration%407.1.3), it was no longer being handled correctly.
The fix is simple though: call `dedent` as a function, rather than a string tag. [This was actually a bug in `dedent` that was fixed relatively recently](https://github.com/dmnd/dedent/pull/91), hence the version bump.
I was stumped for a while trying to reproduce this within VE's test suite. I was seeing identical output between `dedent` and `outdent`. I then realised that …
> `addFileScope`: Don't mangle non-template strings that contain newlines

- .changeset/four-humans-hammer.md
- packages/css/src/conditionalRulesets.ts
- packages/css/src/transformCss.test.ts
Fixes #1417.
This fix doesn't preserve the separate declarations, but AFAIK this doesn't have any practical effect on the CSS, other than making it smaller. I also don't think it would be possible to preserve the separate declarations without refactoring how the merging works, so I'm happy with this solution for now.
> css: Fix conditional rule merging bug

- site/docs/integrations/next.md
This config example doesn't work. I've aligned it to be written in the same style as the other examples on this page.
Fixes #1428.
Fixes #1429.
> docs: Fix incorrect Next.js configuration

- .changeset/chilled-paws-shop.md
- packages/vite-plugin/src/index.ts
Fixes https://github.com/vanilla-extract-css/vanilla-extract/issues/1427
Tracked down an issue where .css.ts files that are imported by .css.ts files trigger updates, but changes aren't propagated to rendered component during development. By invalidating all deps of a .css.ts file, instead of just the root file, the expected behavior occurs.
> Fix changes to nested imports not updating styles during development

- site/src/Chevron/Chevron.css.ts
- site/src/ColorModeToggle/ColorModeToggle.css.ts
- site/src/DocsPage/DocsPage.css.ts
- site/src/GitHubStars/GitHubStars.tsx
- site/src/HomePage/HomePage.css.ts
* `Chevron.css.ts`: using styleVarinats is better than object which has many `style` in vanilla-extract so i change object to styleVariants in `direction`
* `ColorModeToggle.css.ts`: using `assignVars` is clear than creating many `createVar`s so i change it with `createThemeContract` like `SyntaxHighlighter.css.ts`
* `DocsPage.css.ts`, `HomePage.css.ts`: remove spread syntax in responsiveStyle for unity with other constants
* `GithubStars.tsx`: getCount use once and we does not use this in useEffect, using iife is more simple than creating getCount and use this once
> refactor(site): add styleVariants, change createVar to assignVars, change to iife, take unity

- .changeset/plenty-hairs-change.md
- package.json
- packages/esbuild-plugin-next/package.json
- packages/esbuild-plugin/package.json
- packages/integration/package.json
- packages/jest-transform/package.json
- packages/rollup-plugin/package.json
- pnpm-lock.yaml
- test-helpers/package.json
Widens the `esbuild` dependency range in a few packages to include `~0.22.0` and `~0.23.0`. Also updates some `esbuild` dev deps, and a few monorepo deps that depend on `esbuild` so we don't end up with multiple versions of `esbuild` in the lockfile.
> Widen `esbuild` dependency range, update dev deps

- site/src/ColorModeToggle/ColorModeToggle.tsx
* in british "colour" is right but vanilla-extract is using in international so i think naming "color" is good more than.
* we named component as "ColorModeToggle" so i think naming "color" is in contextually consistent.
> fix(site/ColorModeToggle/ColorModeToggle.tsx): change ColorMode title colour to color

- .changeset/cold-eyes-rescue.md
- packages/css/src/simplePseudos.ts
> fix(ISSUE-1474): add -webkit-calendar-picker-indicator pseudoclass

- .changeset/twelve-pans-dress.md
- fixtures/features/src/html.ts
- fixtures/features/src/index.ts
- packages/vite-plugin/src/index.ts
Fixes #1481.
#1438 broke HMR invalidation for files that don't end in `.css.ts`, e.g. `.css.tsx` which is a [valid](https://github.com/vanilla-extract-css/vanilla-extract/blob/d271b9f9e0e4f0bc668ded78bb15938627957a7a/packages/integration/src/filters.ts#L3), though uncommon, VE file extension.
This PR fixes this issue, as well as enables vite HMR for the `features` fixture to enable easier testing of HMR in the future.
> vite: Fix HMR invalidation

- .changeset/config.json
- Use the calculated version when publishing snapshots. This means a patch release snapshot for a package on `1.0.0` will be `1.0.1-etc` rather than `0.0.0-etc`. This aligns better with semver, and is just nicer to work with IMO.
- There's now proper support for ignoring private packages, so I've enabled that. This cuts down on noise in version packages PRs.
> Update changeset config

- .changeset/vite-plugin-react-router.md
- packages/vite-plugin/src/index.ts
Similar to https://github.com/vanilla-extract-css/vanilla-extract/pull/1308.
Omit React-Router plugin for DevServer in Vanilla-Extract Vite plugin, as React-Router plugin throws when launched without Configuration file. (just like the Remix plugin)
> fix(vite-plugin): Omit React-Router v7 plugin for DevServer

- .changeset/flat-humans-hammer.md
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
Fixes #1501.
Depending on the hash of a scoped classname, a selector such as `&&` would end up transformed into a selector that was not scoped to the classname represented by `&`, which would cause an [invalid selector error](https://github.com/vanilla-extract-css/vanilla-extract/blob/704724367568055478469429f817dc60b5fef44c/packages/css/src/validateSelector.ts#L24).
An example from the test case I added involves the local classnames `debugName_hash1` and `debugName_hash1d`. The `&&` selector would become `debugName_hash1debugName_hash1`, which contains `debugName_hash1d` as a substring.
When this occurs, the local classname search returns 3 results of the form:
```
[
[14, ['debugName_hash1']],
[15, ['debugName_hash1d']],
[29, ['debugName_hash1']],
]
```
Note that we iterate over these …
> Fix incorrect selector transformation when a substring of a selector matches another local classname

- .changeset/nasty-wasps-tie.md
- fixtures/themed/src/themes.css.ts
- packages/css/src/theme.ts
- packages/css/src/types.ts
- packages/rollup-plugin/test/__snapshots__/rollup-plugin.test.ts.snap
- site/docs/api/create-theme.md
- site/docs/global-api/create-global-theme.md
- tests/e2e/themed.playwright.ts-snapshots/themed-esbuild--development.css
- tests/e2e/themed.playwright.ts-snapshots/themed-esbuild--production.css
- tests/e2e/themed.playwright.ts-snapshots/themed-esbuild-next--development.css
- tests/e2e/themed.playwright.ts-snapshots/themed-esbuild-next--production.css
- tests/e2e/themed.playwright.ts-snapshots/themed-mini-css-extract--development.css
- tests/e2e/themed.playwright.ts-snapshots/themed-mini-css-extract--production.css
- tests/e2e/themed.playwright.ts-snapshots/themed-parcel--development.css
- tests/e2e/themed.playwright.ts-snapshots/themed-parcel--production.css
- tests/e2e/themed.playwright.ts-snapshots/themed-vite--production.css
[Original discussion](https://github.com/vanilla-extract-css/vanilla-extract/discussions/1472).
This is currently possible in VE using existing APIs ([example](https://github.com/vanilla-extract-css/vanilla-extract/discussions/1472#discussioncomment-11000308)), however it's not exactly ergonomic, nor is it obvious that this is possible, so first-class support would be nice.
Sprinkles supports layers via an `@layer` property, so I implemented the same thing for `createTheme` and `createGlobalTheme`.
**EXAMPLE USAGE**:
```ts
// themes.css.ts
import { createTheme, createGlobalTheme, layer } from '@vanilla-extract/css';
export const themeLayer = layer();
export const [themeA, vars] = createTheme({
'@layer': themeLayer,
color: {
brand: 'blue'
},
font: {
body: 'arial'
}
});
export const vars2 = …
```
> `createTheme`, `createGlobalTheme`: Add support for assigning themes to a layer

- site/docs/api/keyframes.md
I broke this in #1092 when trying to make changes in a code suggestion. https://github.com/vanilla-extract-css/vanilla-extract/pull/1092/commits/a0a4b948da64969aa669fe98a1503ea5723f59a9#diff-c74ddbc9d698db9ae1cd5e784a93f9392240cade1b5ce2aec615fb1f8d9d8db7L36
> Fix broken compiled example in `keyframes` docs

- .github/workflows/validate.yml
* We are using `ubuntu-latest` and `windows-latest` in the `validate.yml`. Therefore, it would be better to use `macos-latest` for macOS as well.
> chore(.github/workflows/validate.yml): change playwright runs-on 'macos-14' to 'macos-latest'

- site/src/Code/ErrorHighlighter.css.ts
In Safari, specifying `text-decoration-style` in the `text-decoration` shorthand is [only supported if you use the prefixed `-webkit-text-decoration`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration#browser_compatibility). The production site currently looks like this in Safari (no dashed underline):
With this fix it will match Chrome (Firefox's dashes are a bit wider):
> site: Fix code editor text decoration style in Safari

- .changeset/flat-waves-talk.md
- packages/esbuild-plugin-next/package.json
- packages/esbuild-plugin/package.json
- packages/integration/package.json
- packages/jest-transform/package.json
- packages/rollup-plugin/package.json
- pnpm-lock.yaml
- test-helpers/package.json
Just the usual `esbuild` dep range increase to support the new minor version. Also updated `esbuild` dev deps to the latest version.
See https://github.com/vanilla-extract-css/vanilla-extract/pull/1436 for prior art.
> Extend `esbuild` dependency range, update `esbuild` dev deps

- .changeset/soft-kiwis-pull.md
- packages/css/src/transformCss.test.ts
- packages/css/src/transformCss.ts
Fixes #1528.
`@container` queries that contain `selectors` are correctly generated, but the inverse is not true. We support `@media` queries inside `selectors`, so I see no reason not to also support `@container` queries inside `selectors`.
> Fix `@container` queries inside `selectors`

- .changeset/tame-hornets-turn.md
- packages/integration/src/compiler.ts
Fixes #1453. Fixes #1519.
[Astro mark `cssesc` as external during dev time](https://github.com/withastro/astro/blob/0879cc2ce7e15a2e7330c68d6667d9a2edea52ab/packages/astro/src/core/create-vite.ts#L86) to work around this issue, so we should too. As far as the compiler is concerned, we don't differentiate between dev and non-dev, so I've chosen to omit the logic that only marks `cssesc` as external during dev time.
This issue was actually introduced by #1395 as it resulted in astro's vite plugins being propagated through to the `vite-node` server (not sure which specific plugin is the culprit though). Filtering those plugins out _also_ fixes this bug, but IMO this targeted fix is the better option.
> `vite`: Fix astro dev server page load error by marking `cssesc` as external in the `vite-node` server

- .changeset/three-shirts-knock.md
I keep forgetting that [admonitions](https://github.com/orgs/community/discussions/16925) don't format correctly in changelogs.
> Remove github admonitions from changesets

- .changeset/chatty-penguins-carry.md
- packages/esbuild-plugin-next/package.json
- packages/esbuild-plugin/package.json
- packages/integration/package.json
- packages/jest-transform/package.json
- packages/rollup-plugin/package.json
- pnpm-lock.yaml
- test-helpers/package.json
- test-helpers/src/startFixture/esbuild.ts
Resolves #1544.
The only relevant change in [esbuild 0.25.0](https://github.com/evanw/esbuild/releases/tag/v0.25.0) was the `serve` API returning an array of `hosts` rather than a single `host`.
See #1530 for a previous similar change.
> Extend esbuild dependency range to include `~0.25.0`, update esbuild dev deps

- .changeset/nervous-cougars-glow.md
- .changeset/two-kids-relax.md
- benchmarks/README.md
- benchmarks/package.json
- benchmarks/src/css-var-string-literal.ts
- benchmarks/tsconfig.json
- packages/private/src/types.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixes #1556.
Simplifying the CSS var function fallback string literal type from
```ts
`var(--${string}, ${string | number})`
```
to
```ts
`var(--${string}, ${string})`
```
drastically improves type-checking in certain cases. For example, when passing a template literal that interpolates a CSS variable into a `style` property multiple times:
```ts
// example.css.ts
import { style, createVar } from "@vanilla-extract/css";
const px = createVar();
export const mask = style({
mask: `
repeating-linear-gradient(45deg, #0005 0 calc(1 * ${px}), black calc(2 * ${px}) calc(3 * ${px}), #0005 calc(4 * ${px}) calc(5 * ${px})) no-repeat,
repeating-linear-gradient(-45deg, #0005 0 calc(1 * ${px}), black calc(2 * ${px}) calc(3 * ${px}), #0005 calc(4 * ${px}) calc(5 * ${px})) no-repeat
`,
});
```
This …
> css: Improve type-checking performance of `CSSVarFunction`

- .changeset/warm-seahorses-taste.md
- packages/css/src/types.ts
Types that uses `WithQueries<StyleType>` are defined like `StyleType & WithQueries<StyleType>`, for example:
https://github.com/vanilla-extract-css/vanilla-extract/blob/221f07f83844a238604a00e4c2d3c75eb7f087ba/packages/css/src/types.ts#L73
while `WithQueries<StyleType>` is defined as:
https://github.com/vanilla-extract-css/vanilla-extract/blob/221f07f83844a238604a00e4c2d3c75eb7f087ba/packages/css/src/types.ts#L62
Additional `StyleType &` is unnecessary, as `StyleType & WithQueries<StyleType>` is `StyleType & StyleType & AllQueries<StyleType>`.
> Remove unnecessary intersections

- .npmrc
- package.json
- pnpm-workspace.yaml
- `strict-peer-dependencies` has defaulted to `false` in PNPM for a while now, so the explicit config has been removed
- `volta` is effectively unmaintained, `corepack` (or more generics tool that use `corepack` like `asdf` or `mise`) is likely going to be recommendation going forward
- `prefer-workspace-packages` should've been in `.npmrc`, but it's now available in camel case in `pnpm-workspace.yaml`. It wasn't doing anything before, but even now I don't think it affects much, we're already using the workspace protocol for package references.
> Use pnpm v10, move pnpm config to `pnpm-workspace.yaml`, remove `volta` config

- scripts/build-dts.ts
- scripts/copy-next-plugin.ts
- scripts/copy-readme-to-packages.ts
- scripts/package.json
Changes are primarily indentation related now that we don't need to use IIFEs and can instead use top-level `await`. Additionally, `packages/compiler` is now excluded from the copy READMEs script as currently that package is published with the top-level README.
> Convert `scripts` package to `type: "module"`

- .changeset/kind-chicken-battle.md
- .changeset/wet-swans-rush.md
- packages/compiler/src/compiler.ts
- packages/vite-plugin/src/index.ts
- test-helpers/src/startFixture/esbuild.ts
Closes #1327.
Both the parent vite dev server and the compiler can have independent file watchers configured. During a build, the compiler doesn't need to watch files, so a new `enableFileWatcher` option has been exposed on `createCompiler`. The vite plugin sets this to `false` during a non-watched build.
I tried exposing a module invalidation method on a the compiler so that the parent vite server can invalidate it based on events from its watcher. This would lets us permanently disable the compiler's watcher in the vite plugin. However I couldn't get it to work. It resulted in HMR not working at all, and even a page refresh wouldn't update CSS :shrug:.
I've also modified how we run `esbuild` fixtures to take advantage of the documented [live …
> `vite`: Disable the compiler's file watcher during builds

- .github/workflows/deploy-site.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/validate.yml
* Since `vanilla-extract` is an official open source library, I replaced the alias command `pnpm i` with the full command `pnpm install` for clarify.
> ci(.github/workflows): replace 'pnpm i' with 'pnpm install'

- .changeset/old-dragons-sort.md
- packages/compiler/package.json
- pnpm-lock.yaml
Vite 7 (currently in beta) includes a small breaking change that affects vite-node. Because of that, currently the plugin cannot be used with Vite 7.
This PR updates vite-node to v3.2.2 so that the plugin can be used with Vite 7. vite-node 3.2 is compatible with Vite 5 and Vite 6 so this change should not affect older versions.
It's still a beta version, but merging this PR will help keeping the ecosystem-ci green and helps us find any regression faster (it was caught indirectly via waku).
> Update vite-node to v3.2.2

- scripts/build-dts.ts
- scripts/copy-next-plugin.ts
- scripts/copy-readme-to-packages.ts
As per [recommendation](https://github.com/SuperchupuDev/tinyglobby/issues/127#issuecomment-2957770469) from the `tinyglobby` maintainer.
> Set `expandDirectories: false` when using `tinyglobby` to more accurately reflect `fast-glob` behaviour

- .changeset/giant-apples-know.md
- examples/remix/package.json
- fixtures/themed/src/index.ts
- package.json
- packages/compiler/package.json
- packages/rollup-plugin/test/__snapshots__/rollup-plugin.test.ts.snap
- packages/vite-plugin/package.json
- pnpm-lock.yaml
- test-helpers/package.json
[Vite v7 was released on June 24th](https://github.com/vitejs/vite/releases/tag/v7.0.0). This PR adds support for the new major version by widening the peerDependencies range.
- Update `vitest` to `3.2.4` (vitest's vite v7 support was added in [v3.2.0](https://github.com/vitest-dev/vitest/releases/tag/v3.2.0).
- Update `vite-plugin-inspect` to `11.3.0` for vite v7 support (this version drops support for vite v5 but this is only used in test content and doesn't seem to affect anything)
- Add `|| ^7.0.0` to the `vite` peerDependencies.
- Use Vite v7 as the installed version when developing vanilla-extract.
vite-node was already bumped to a version that supports Vite v7 in #1605.
- The jest unit tests are failing, as the `"1/4": "styles_opacity_1/4__jteyb17"` key is no longer present in the …
> Support Vite 7

- .changeset/breezy-poets-matter.md
- packages/rollup-plugin/src/index.ts
Hi 👋 
Without source map contents included [(which is the default behavior of rollup sourcemaps)](https://rollupjs.org/configuration-options/#output-sourcemapexcludesources) it makes them less useful. 
For example if you explore [the `app.css` and `app.css.map`](https://github.com/user-attachments/files/21537058/before.zip) for the `fixtures/react-library-example` workspace on [https://evanw.github.io/source-map-visualization] the mappings lead to empty files:
[With this PR the mappings now preserve the CSS that were initially omitted](https://github.com/user-attachments/files/21537218/after.zip):
Richer sourcemaps are especially useful when vanilla extract is the first step, and later on `lightningcss`, `cssnano` or `postcss` is operating on the extracted CSS asset. In those scenarios …
> fix: include content in css sourcemap when extracting
