README.md
=> Update README to mention the Gatsby plugin

docs/treat-migration-guide.md
=> Add note about CSS handling and URLs to treat migration guide

.changeset/dirty-brooms-vanish.md, packages/private/src/walkObject.ts
=> Fix createThemeVars when using null values

packages/sprinkles/README.md
=> Fix typos in Sprinkles readme

packages/sprinkles/README.md
Fixes a couple of minor issues raised in this Twitch stream: https://www.twitch.tv/videos/1015616142?sr=a&t=1059s
=> Update Sprinkles example in readme

.changeset/funny-candles-sin.md, packages/babel-plugin/src/index.ts, packages/integration/src/compile.ts, packages/integration/src/processVanillaFile.ts
=> Improved Windows support

.changeset/empty-squids-build.md
=> Release v1

.changeset/dull-oranges-refuse.md, packages/integration/src/packageInfo.ts
Where the ~~streets~~packages have no name
=> Continue searching for package.json if one is found with no name

.changeset/funny-pets-laugh.md, packages/css/package.json, packages/css/src/validateSelector.test.ts, packages/css/src/validateSelector.ts, yarn.lock
=> Fix :where/:is in scoped selectors

.changeset/rare-rings-applaud.md, packages/sprinkles/src/types.ts
=> Sprinkles: Fix responsiveArray length of 4

.changeset/eleven-colts-admire.md, packages/css/src/theme.ts, packages/css/src/types.ts, packages/css/src/vars.ts, packages/private/src/index.ts, packages/private/src/types.ts
=> Fix `createGlobalTheme` types when accepting an existing contract

.changeset/weak-planets-rush.md, packages/css/src/types.ts, tests/types/type-tests.ts
=> Fix type errors with nested null values in theme contracts

.github/workflows/release.yml
Mainly to fix the `Release - undefined` notification in slack 😄
=> Upgrade changesets action

README.md, site/docs/styling-api.md
=> Add style to import

.changeset/weak-pants-prove.md, packages/css/src/transformCss.test.ts, packages/css/src/transformCss.ts
See changeset and tests for details.
=> Automatically add quotes to `content` values

.changeset/early-baboons-serve.md, .changeset/rude-actors-obey.md, packages/recipes/src/createRuntimeFn.ts, packages/recipes/src/index.ts, packages/recipes/src/types.ts, tests/recipes/recipes.css.ts, tests/recipes/recipes.test.ts
Also add jest tests for recipes
Resolves #378
=> Handle undefined in recipes, improve recipe debug IDs

.changeset/support-mjs-pls.md, packages/integration/src/filters.ts
resolves https://github.com/seek-oss/vanilla-extract/issues/388 cc @markdalgleish @mattcompiles
=> fix: support `*.css.mjs`

tests/stylesheets/__snapshots__/recipes.test.ts.snap, tests/stylesheets/__snapshots__/sprinkles.test.ts.snap, tests/stylesheets/__snapshots__/themed.test.ts.snap, tests/stylesheets/__snapshots__/unused-modules.test.ts.snap, tests/stylesheets/recipes.test.ts, tests/stylesheets/sprinkles.test.ts, tests/stylesheets/themed.test.ts, tests/stylesheets/unused-modules.test.ts
=> Update the test names

package.json
=> Add command in to release

.changeset/old-phones-kneel.md, babel-jest.config.js, babel.config.js
=> Transpile packages that contain browser code

.changeset/spicy-insects-approve.md, examples/next/next-env.d.ts, examples/next/package.json, examples/next/tsconfig.json, packages/next-plugin/package.json, packages/next-plugin/src/index.js, pnpm-lock.yaml
=> next-plugin: Bump minimum version of Next to 12.0.5

.changeset/grumpy-rockets-cover.md, packages/recipes/src/createRuntimeFn.ts, tests/recipes/recipes.css.ts, tests/recipes/recipes.test.ts
=> Ensure missing boolean variants don't return 'undefined' in class name

.changeset/clever-fishes-ring.md, packages/vite-plugin/src/index.ts
=> vite: Fix style imports from parent directories

site/src/GitHubStars/GitHubStars.tsx, site/src/HomePage/HomePage.tsx
~Also opting for `bigger` twitter avatars (73x73) given we only display at 60x60. Perf ftw~ 🏎️ 
Opting for 200x200 twitter avatars because high DPI. Still perf though 🐌
=> Fix GitHub star count & broken twitter avatar

.changeset/quiet-games-explain.md, packages/recipes/src/createRuntimeFn.ts, tests/recipes/recipes.test.ts
=> Fix compound variants not applying when default variants get undefined

.changeset/cold-phones-deny.md, packages/vite-plugin/src/index.ts
fixes: #698
@pakholeung37 I added you as a co-author on the commit since you essentially posted the fix in this issue 😃
=> vite: Absolute module id for invalidation

.changeset/forty-swans-fail.md, packages/css/src/transformCss.ts, packages/css/src/validateMediaQuery.test.ts, packages/css/src/validateMediaQuery.ts
=> Validate duplicate @media in media queries

.github/workflows/snapshot.yml, package.json
This is a direct copy of [braid's version](https://github.com/seek-oss/braid-design-system/blob/master/.github/workflows/snapshot.yml).
=> Add a snapshots workflow

packages/css/src/fileScope.ts
update documentation link to https://vanilla-extract.style/documentation/getting-started
=> Update not found link documentation

.changeset/fluffy-steaks-yell.md, fixtures/sprinkles/src/index.ts, fixtures/sprinkles/src/styles.css.ts, packages/sprinkles/src/index.ts, site/docs/packages/sprinkles.md, tests/stylesheets/__snapshots__/sprinkles.test.ts.snap
This allows you to create utility classes scoped to container queries—pretty neat!
**Example usage**
```ts
import {
createContainer,
style
} from '@vanilla-extract/css';
import { defineProperties } from '@vanilla-extract/sprinkles';
const containerName = createContainer();
export const container = style({
containerName,
containerType: 'size'
});
const containerProperties = defineProperties({
conditions: {
smallContainer: {},
mediumContainer: {
'@container': `${containerName} (min-width: 768px)`
},
largeContainer: {
'@container': `${containerName} (min-width: 1024px)`
}
},
defaultCondition: 'smallContainer'
// etc.
});
```
You can then consume them like this:
```ts
<div
className={sprinkles({
display: "flex",
flexDirection: {
smallContainer: "column",
mediumContainer: "row",
},
})}
>
... …
```
=> Sprinkles: Add support for container query conditions

.github/workflows/deploy-site.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, .github/workflows/validate.yml, pnpm-lock.yaml, site/package.json
I have already disabled builds in the Netlify dashboard so this is safe to merge. 
Check out a draft deploy here: https://633146a89dc9973468f7c5f4--vanilla-extract-css.netlify.app
=> Move site deployments to use netlify-cli

.changeset/stale-feet-sniff.md, packages/vite-plugin/package.json, pnpm-lock.yaml
=> vite-plugin: Add vite 3 to peer dependencies

site/docs/packages/sprinkles.md
- Fixed incorrect file reference
- Fixed return values of `normalizeResponsiveValue`
=> Fix `normalizeResponsiveValue` example in sprinkles docs

.changeset/smart-dingos-search.md, packages/vite-plugin/src/index.ts
This adds the qwik plugin to the SSR list, the rest happens automatically.
=> vite-plugin: support Qwik

site/docs/global-api/create-global-theme.md
Hey, friends 👋🏻
Saw this small typo as I was reading along. Cheers!
=> Fix small typo in docs

.changeset/tasty-panthers-cheer.md, .npmrc, packages/jest-transform/src/index.ts, site/docs/overview/test-environments.md
This solution published by @jd-oconnor is very elegant, and I think it's worth including in the documentation. See https://github.com/vanilla-extract-css/vanilla-extract/issues/962#issuecomment-1384742733
=> Add CSS transformer solution to Jest docs

site/src/DocsPage/DocsPage.css.ts, site/src/mdx-components.css.ts, site/src/mdx-components.tsx
Hoping this supports deep linking in the upcoming search PR.
=> site: Move ids to headings

packages/css/src/transformCss.test.ts
Follow-up from https://github.com/vanilla-extract-css/vanilla-extract/pull/955#discussion_r1150011803
=> Clean up test snapshots

packages/css/src/transformCss.test.ts, site/docs/overview/styling.md, tests/compiler/compiler.vitest.test.ts, tests/compiler/fixtures/selectors/getter.css.ts
The solution was proposed by @graup in https://github.com/vanilla-extract-css/vanilla-extract/pull/1081#issuecomment-1556378286
=> Add Circular Selectors section to docs

.changeset/loud-zoos-allow.md, packages/css/package.json, packages/css/src/transformCss.test.ts, pnpm-lock.yaml
=> Fix psuedo element validator by updating css-what

.changeset/integration-deps.md
=> Update affected integrations

examples/webpack-react/webpack.config.js
Fixes #1280.
Tested by forking the sandbox and adding the config.
=> Fix sandbox

site/docs/overview/getting-started.md
Hi there! 
While reading the document, I noticed that the file names in the code were different. so I just made a small change. 😃
=> docs: fix filename in the code

.changeset/little-turkeys-dream.md, examples/webpack-react/package.json, package.json, packages/babel-plugin-debug-ids/package.json, packages/integration/package.json, pnpm-lock.yaml, site/package.json, test-helpers/package.json
Upgrade Babel dependencies to patch critical level vulnerability in babel/traverse
https://github.com/advisories/GHSA-67hx-6x53-jw92
=> update babel dependencies

site/docs/integrations/webpack.md
Otherwise I get a syntax error
=> docs: clarify Webpack usage when using multiple CSS loaders

.changeset/pink-socks-switch.md, packages/esbuild-plugin-next/package.json, packages/esbuild-plugin/package.json, packages/integration/package.json, packages/jest-transform/package.json, packages/rollup-plugin/package.json, pnpm-lock.yaml, test-helpers/package.json
- https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0200 (deno only)
- https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0210 (safe rather than sorry, so release as breaking)
Tests pass locally, so presumably this is safe 😀
=> Extend esbuild dependency range

.changeset/tame-suits-refuse.md, packages/recipes/src/types.ts
=> fix(recipes): Allow `undefined` for variants

.changeset/twenty-bananas-relate.md, package.json, packages/rollup-plugin/package.json, packages/rollup-plugin/src/index.ts, packages/rollup-plugin/test/__snapshots__/rollup-plugin.test.ts.snap, pnpm-lock.yaml, scripts/build-dts.ts
Pretty straightforward. Will comment on any changes that need clarification.
=> Update rollup and rollup plugins

examples/webpack-react/package.json, pnpm-lock.yaml, site/package.json, site/webpack.config.js, test-helpers/package.json, test-helpers/src/startFixture/webpack.ts
Update webpack-related deps such as loaders/plugins and the dev server.
=> Update webpack-related deps

pnpm-lock.yaml, scripts/build-dts.ts, scripts/copy-next-plugin.ts, scripts/copy-readme-to-packages.ts, scripts/package.json
[`tinyglobby`](https://www.npmjs.com/package/tinyglobby) is "A fast and minimal alternative to globby and fast-glob, meant to behave the same way."
=> Replace `fast-glob` with `tinyglobby`
